version: '3'
services:
  db:
    container_name: postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dataset_generator
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: feriel@admin.com
      PGADMIN_DEFAULT_PASSWORD: feriel
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
  dataset_generator_service:
    build:
      context: ./
    ports:
      - "80:80"
