version: '3'
services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: datasetgenerator
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: feriel@admin.com
      PGADMIN_DEFAULT_PASSWORD: feriel
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"