spring:
  datasource:
    url: jdbc:postgresql://database-postgres:5432/dataset_generator
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
file:
  extensions: .wav, .mp3
minimumFields: 7
