name: Cleanup Expired Repositories

on:
  schedule:
    - cron: '*/5 * * * *'
    
jobs:
  cleanup-repositories:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch all repositories
      run: |
